language: c
compiler:
    - clang
    - gcc
script: make && if [ $TRAVIS_OS_NAME = linux ]; then make clean; make -C v6502 CC=avr-gcc lib; make -C dis6502 CC=avr-gcc lib; make -C ld6502 CC=avr-gcc lib; fi
install:
    - if [ $TRAVIS_OS_NAME = osx ]; then brew install doxygen; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libedit-dev libncurses5-dev doxygen gcc-avr binutils-avr avr-libc; fi
os:
    - linux
    - osx
